/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visão;

import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class PaginaInicial extends javax.swing.JFrame {

    /**
     * Creates new form PaginaInicial
     */
    public PaginaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jBAncos = new javax.swing.JComboBox<>();
        jProx = new javax.swing.JButton();
        jFundo = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Escolha o Banco");
        getContentPane().setLayout(null);

        jBAncos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nenhum", "Bradesco", " " }));
        jBAncos.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jBAncosComponentAdded(evt);
            }
        });
        getContentPane().add(jBAncos);
        jBAncos.setBounds(100, 110, 150, 20);

        jProx.setText("Próximo");
        jProx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jProxActionPerformed(evt);
            }
        });
        getContentPane().add(jProx);
        jProx.setBounds(120, 160, 110, 23);

        jFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage2/fundo-de-tela-azul-verde-claro-fundos-azuis-350163.jpg"))); // NOI18N
        getContentPane().add(jFundo);
        jFundo.setBounds(-40, -40, 540, 540);

        setSize(new java.awt.Dimension(381, 291));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBAncosComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jBAncosComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jBAncosComponentAdded

    private void jProxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jProxActionPerformed
        Boleto janela = new Boleto();
        if(jBAncos.getSelectedItem().equals("Nenhum")){
            JOptionPane.showMessageDialog(null, "Escolha um banco ", "ESCOLHA INVALIDA", HEIGHT);
        } else {
            janela.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jProxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaginaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jBAncos;
    private javax.swing.JLabel jFundo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jProx;
    // End of variables declaration//GEN-END:variables
}
